-- MySQL Script generated by MySQL Workbench
-- Mon Apr 29 17:51:20 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
--CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE donaElisa ;

-- -----------------------------------------------------
-- Table donaElisa.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS donaElisa.Cliente (
  CPF VARCHAR(14) NOT NULL,
  ClienteNO VARCHAR(50) NOT NULL,
  PRIMARY KEY (CPF))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table donaElisa.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS donaElisa.Endereco (
  Cidade VARCHAR(50) NOT NULL,
  Bairro VARCHAR(50) NOT NULL,
  Rua VARCHAR(50) NOT NULL,
  UF CHAR(2) NOT NULL,
  Numero CHAR(4) NOT NULL,
  Complemento VARCHAR(45) NULL,
  Cliente_CPF VARCHAR(14) NOT NULL,
  PRIMARY KEY (Cliente_CPF),
  CONSTRAINT fk_Endereco_Cliente
    FOREIGN KEY (Cliente_CPF)
    REFERENCES donaElisa.Cliente (CPF)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table donaElisa.`Telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS donaElisa.Telefone (
  NRO VARCHAR(14) NOT NULL,
  Cliente_CPF VARCHAR(14) NOT NULL,
  PRIMARY KEY (Cliente_CPF),
  CONSTRAINT fk_Telefone_Cliente1
    FOREIGN KEY (Cliente_CPF)
    REFERENCES donaElisa.Cliente (CPF)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table donaElisa.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS donaElisa.Usuario (
  CodUsuario INT NOT NULL,
  NoUsuario VARCHAR(50) NOT NULL,
  Senha VARCHAR(50) NOT NULL,
  TipoUsuario VARCHAR(20) NOT NULL,
  PRIMARY KEY (CodUsuario))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table donaElisa.`CatPratos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS donaElisa.CatPratos (
  CodCategoria INT NOT NULL,
  NoCategoria VARCHAR(50) NOT NULL,
  Descricao VARCHAR(50) NULL,
  PRIMARY KEY (CodCategoria))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table donaElisa.`Pratos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS donaElisa.Pratos (
  CodPrato INT NOT NULL,
  NoPrato VARCHAR(50) NOT NULL,
  Descricao VARCHAR(50) NOT NULL,
  UnidadePrato CHAR(2) NOT NULL,
  CatPratos_CodCategoria INT NOT NULL,
  PRIMARY KEY (CodPrato),
  INDEX fk_Pratos_CatPratos1_idx (CatPratos_CodCategoria ASC),
  CONSTRAINT fk_Pratos_CatPratos1
    FOREIGN KEY (CatPratos_CodCategoria)
    REFERENCES donaElisa.CatPratos (CodCategoria)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table donaElisa.`Encomenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS donaElisa.Encomenda (
  CodEncomenda INT NOT NULL,
  QntdItens INT NOT NULL,
  Status VARCHAR(50) NOT NULL,
  DtaEntrega DATE NOT NULL,
  HoraEntrega DATETIME NOT NULL,
  Cliente_CPF VARCHAR(14) NOT NULL,
  PRIMARY KEY (CodEncomenda),
  INDEX fk_Encomenda_Cliente1_idx (Cliente_CPF ASC),
  CONSTRAINT fk_Encomenda_Cliente1
    FOREIGN KEY (Cliente_CPF)
    REFERENCES donaElisa.Cliente (CPF)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table donaElisa.`ItensEncomendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS donaElisa.ItensEncomendas (
  CodItensEncomendas INT NOT NULL,
  Qntd INT NOT NULL,
  Pratos_CodPrato INT NOT NULL,
  Encomenda_CodEncomenda INT NOT NULL,
  PRIMARY KEY (CodItensEncomendas),
  INDEX fk_ItensEncomendas_Pratos1_idx (Pratos_CodPrato ASC),
  INDEX fk_ItensEncomendas_Encomenda1_idx (Encomenda_CodEncomenda ASC),
  CONSTRAINT fk_ItensEncomendas_Pratos1
    FOREIGN KEY (Pratos_CodPrato)
    REFERENCES donaElisa.Pratos (CodPrato)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_ItensEncomendas_Encomenda1
    FOREIGN KEY (Encomenda_CodEncomenda)
    REFERENCES donaElisa.Encomenda (CodEncomenda)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
